export const projects = [
  {
    number: '01',
    title: 'Weather App Project',
    type: 'Python Application',
    audience: 'Python Internship Project at OASIS INFOBYTE',
    year: '2026',
    image: '/4.jpg',
    className: 'project-blue',
    description: 'This project focuses on creating a weather application using Python, featuring real-time data fetching, interactive UI, and responsive design. This project helped me dive deeper into Python development, API integration, GUI design, and real-time data handling. Building this application improved both my coding skills and problem-solving approach',
    skills: ['Python', 'API Integration', 'Tkinter', 'Data Visualization', 'UI Design'],
  },
  {
    number: '02',
    title: 'BMI Calculator Pro',
    type: 'Python Application',
    audience: 'Python Internship Project at OASIS INFOBYTE',
    year: '2026',
    image: '/5.jpg',
    className: 'project-blue',
    description: 'BMI Calculator Pro is a Python desktop application developed using Tkinter, SQLite, and Matplotlib with a focus on user-friendly GUI design, modular programming, database integration, and graphical visualization.',
    skills: ['Python', 'Tkinter', 'SQLite', 'Matplotlib', 'Desktop UI'],
  },
  {
    number: '03',
    title: 'Early Detection of Dementia',
    type: 'MERN Application',
    audience: 'College Project ',
    year: '2025',
    image: '/3.jpg',
    className: 'project-blue',
    description: 'This project focuses on creating hybrid machine learning models that combine genetic data and neuroimaging analysis for early detection of dementia. Using techniques like feature selection for genetic markers and CNNs for analyzing MRI scans, the model improves diagnostic accuracy by leveraging complementary insights from both data types.',
    skills: ['React', 'Node.js', 'MongoDB', 'ML Models', 'Healthcare Analytics'],
  },
  {
    number: '04',
    title: 'Bedanta Agri',
    type: 'Full Stack MERN E-Commerce & Product Management Platform',
    audience: 'Freelance Project',
    year: '2025',
    image: '/2.jpg',
    className: 'project-coral',
    description: 'Designed and developed a full-stack MERN application featuring user authentication, product management, category organization, RESTful APIs, and MongoDB database integration. Created scalable frontend architecture using React and Tailwind CSS while ensuring secure backend operations with Node.js and Express.js.',
    skills: ['React', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS', 'REST API'],
  },
]
